# The URL the site will be built for
title = "ymstnt"
base_url = "https://blog.ymstnt.com"
description = "ymstnt's personal website"
default_language = "en"

theme = "duckquill"
compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
generate_sitemap = true
generate_robots_txt = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

author = "ymstnt"
taxonomies = [{ name = "tags", feed = true}]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
	{ theme = "solarized-dark", filename = "syntax-theme-dark.css" },
	{ theme = "solarized-light", filename = "syntax-theme-light.css" }
]
smart_punctuation = true
bottom_footnotes = true

[search]
index_format = "elasticlunr_json"
# index_format = "fuse_json"

[languages.hu]
title = "ymstnt"
description = "ymstnt weboldala"
generate_feeds = true

taxonomies = [{ name = "tags", feed = true }]

[extra]
styles = [
  "custom.css",
  "mods.css",
]
# Put all your custom variables here
# default_theme = "dark"
accent_color = "#006BB6"

katex = false

toc = true
toc_inline = true
toc_ordered = true

issues_url = "https://github.com/ymstnt/website/issues"
source_url = "https://github.com/ymstnt/website"

show_copy_button = true
show_reading_time = false
show_share_button = false
show_backlinks = false

bio = "I'm a university student studying Computer Science. I enjoy working with Linux, self-hosting, and coding. I also like video games, writing, and maintaining my aquarium."
[extra.nav]

auto_hide = false

show_feed = true
show_theme_switcher = true
show_repo = false

links = [
  { url = "@/about/_index.md", name = "About" },
  { url = "@/projects/_index.md", name = "Projects" },
  { url = "@/uni/_index.md", name = "University" },
  { url = "https://gd.tchfoo.com", name = "gepDrive", external = true}
]

[extra.footer]

socials = [
  { url = "https://github.com/ymstnt", name = "GitHub", icon = "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-linecap='round' stroke-linejoin='round' width='24' height='24' stroke-width='2'%3E%3Cpath d='M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5'%3E%3C/path%3E%3C/svg%3E" },
  { url = "https://social.lol/@ymstnt", name = "Mastodon", icon = "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-linecap='round' stroke-linejoin='round' width='24' height='24' stroke-width='2'%3E%3Cpath d='M18.648 15.254c-1.816 1.763 -6.648 1.626 -6.648 1.626a18.262 18.262 0 0 1 -3.288 -.256c1.127 1.985 4.12 2.81 8.982 2.475c-1.945 2.013 -13.598 5.257 -13.668 -7.636l-.026 -1.154c0 -3.036 .023 -4.115 1.352 -5.633c1.671 -1.91 6.648 -1.666 6.648 -1.666s4.977 -.243 6.648 1.667c1.329 1.518 1.352 2.597 1.352 5.633s-.456 4.074 -1.352 4.944z'%3E%3C/path%3E%3Cpath d='M12 11.204v-2.926c0 -1.258 -.895 -2.278 -2 -2.278s-2 1.02 -2 2.278v4.722m4 -4.722c0 -1.258 .895 -2.278 2 -2.278s2 1.02 2 2.278v4.722'%3E%3C/path%3E%3C/svg%3E" },
  { url = "https://bsky.app/profile/ymstnt.dev", name = "Bluesky", icon = "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-linecap='round' stroke-linejoin='round' width='24' height='24' stroke-width='2'%3E%3Cpath d='M6.335 5.144c-1.654 -1.199 -4.335 -2.127 -4.335 .826c0 .59 .35 4.953 .556 5.661c.713 2.463 3.13 2.75 5.444 2.369c-4.045 .665 -4.889 3.208 -2.667 5.41c1.03 1.018 1.913 1.59 2.667 1.59c2 0 3.134 -2.769 3.5 -3.5c.333 -.667 .5 -1.167 .5 -1.5c0 .333 .167 .833 .5 1.5c.366 .731 1.5 3.5 3.5 3.5c.754 0 1.637 -.571 2.667 -1.59c2.222 -2.203 1.378 -4.746 -2.667 -5.41c2.314 .38 4.73 .094 5.444 -2.369c.206 -.708 .556 -5.072 .556 -5.661c0 -2.953 -2.68 -2.025 -4.335 -.826c-2.293 1.662 -4.76 5.048 -5.665 6.856c-.905 -1.808 -3.372 -5.194 -5.665 -6.856z'%3E%3C/path%3E%3C/svg%3E" },
  { url = "https://codeberg.org/ymstnt", name = "Codeberg", icon = "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' title='Codeberg' stroke-width='2' stroke='currentColor' fill='none' stroke-linecap='round' stroke-linejoin='round' %3E%3Cpath fill='none' d='M12 1A11 11 0 0 0 1 12a11 11 0 0 0 1.7 6.4L12 6l9.3 12.4A11 11 0 0 0 23 12 11 11 0 0 0 12 1Z' /%3E%3Cpath fill='none' d='M21.3 18.4 12 6l4.4 16.8a11 11 0 0 0 4.9-4.4Z' /%3E%3C/svg%3E%0A" },
  { url = "https://steamcommunity.com/id/ymstnt", name = "Steam", icon = "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-linecap='round' stroke-linejoin='round' width='24' height='24' stroke-width='2'%3E%3Cpath d='M16.5 5a4.5 4.5 0 1 1 -.653 8.953l-4.347 3.009l0 .038a3 3 0 0 1 -2.824 3l-.176 0a3 3 0 0 1 -2.94 -2.402l-2.56 -1.098v-3.5l3.51 1.755a2.989 2.989 0 0 1 2.834 -.635l2.727 -3.818a4.5 4.5 0 0 1 4.429 -5.302z'%3E%3C/path%3E%3Ccircle cx='16.5' cy='9.5' r='1' fill='currentColor'%3E%3C/circle%3E%3C/svg%3E" }
]

show_copyright = true
show_powered_by = true
show_source = true
