name: push_cd

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true
    - name: Build
      run: zola build --output-dir $OUT_DIR --force
      #- name: Fix perms for nginx
      #  run: chmod -R 755 $OUT_DIR

